"""changed session_exchanges field name from session_metadata to exchange metadata and separated session_metadata, session_questions and session_contexts as separate fields

Revision ID: 4b1ca7da86ab
Revises: adedfc48975e
Create Date: 2025-06-16 00:40:00.525574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4b1ca7da86ab'
down_revision: Union[str, None] = 'adedfc48975e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structured_result', sa.JSON(), nullable=True))

    with op.batch_alter_table('session_exchanges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_metadata', sa.JSON(), nullable=True))
        batch_op.drop_column('session_metadata')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_questions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('contexts', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('contexts')
        batch_op.drop_column('session_questions')

    with op.batch_alter_table('session_exchanges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_metadata', sqlite.JSON(), nullable=True))
        batch_op.drop_column('exchange_metadata')

    with op.batch_alter_table('parsed_results', schema=None) as batch_op:
        batch_op.drop_column('structured_result')

    # ### end Alembic commands ###
