"""updated user credits and session credits to be integer and added session terminated status

Revision ID: 7d18bd5ad44e
Revises: 4b1ca7da86ab
Create Date: 2025-06-19 02:50:53.151916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7d18bd5ad44e'
down_revision: Union[str, None] = '4b1ca7da86ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sqlite.JSON(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.Integer(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
